FROM python:3.11-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

EXPOSE 7001

# Sekarang modul 'app' benar-benar ada sebagai folder package!
CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "7001", "--reload" ]